---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v4.4.0'
    hooks:
      - id: 'check-added-large-files'
      - id: 'check-ast'
      - id: 'check-case-conflict'
      - id: 'check-json'
      - id: 'check-toml'
      - id: 'check-yaml'
      - id: 'end-of-file-fixer'
      - id: 'trailing-whitespace'
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: 'v0.4.9'
    hooks:
      - id: 'ruff'
      - id: 'ruff-format'
#  - repo: 'https://github.com/pre-commit/mirrors-mypy'
#    rev: 'v1.1.1'
#    hooks:
#      - id: 'mypy'
#        additional_dependencies:
#          - 'types-tabulate'
